server:
  port: 18080

spring:
  redis:
    host: 192.168.0.102
    password:
    port: 6379
    jedis:
      pool:
        max-idle: 100
        max-wait: 1000s
        max-active: -1
        min-idle: 1

